/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_alex_jniexample_MathNativeLib */

#ifndef _Included_com_alex_jniexample_MathNativeLib
#define _Included_com_alex_jniexample_MathNativeLib
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_alex_jniexample_MathNativeLib
 * Method:    fibRNative
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_com_alex_jniexample_MathNativeLib_fibRNative
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_alex_jniexample_MathNativeLib
 * Method:    fibINative
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_com_alex_jniexample_MathNativeLib_fibINative
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_alex_jniexample_MathNativeLib
 * Method:    factRN
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_com_alex_jniexample_MathNativeLib_factRN
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_alex_jniexample_MathNativeLib
 * Method:    factIN
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_com_alex_jniexample_MathNativeLib_factIN
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
